name: Deploy EC2
on:
  push:
    branches: [main]          # despliega solo al hacer push a main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1 ‑ Clona el repo
    - uses: actions/checkout@v4

    # 2 ‑ Carga tu clave SSH privada en el agente
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # 3 ‑ Copia el código (o el artefacto) a la EC2
    - name: Rsync project to EC2
      env:
        HOST:  ${{ secrets.EC2_HOST }}     # p. ej. 54.123.45.67
        USER:  ${{ secrets.EC2_USER }}     # p. ej. ubuntu
        DEST:  ${{ vars.TARGET_DIR }}      # p. ej. /home/ubuntu/app
      run: |
        rsync -az --delete ./ "$USER@$HOST:$DEST"

    # 4 ‑ Ejecuta comandos remotos (build, restart, etc.)
    - name: Remote deploy script
      env:
        HOST:  ${{ secrets.EC2_HOST }}
        USER:  ${{ secrets.EC2_USER }}
        DEST:  ${{ vars.TARGET_DIR }}
      run: |
        ssh "$USER@$HOST" <<'EOF'
        cd "$DEST"
        # ejemplo con Docker Compose
        docker compose pull
        docker compose up -d --build
        # o simplemente: sudo systemctl restart mi‑servicio.service
        EOF

