name: Deploy SPA to EC2
on:
  push:
    branches: [main]


jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # 0. Selecciona la versión de Node que usa tu proyecto
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    # 1. Clona el repo
    - uses: actions/checkout@v4

    # 2. Instala dependencias y compila con Vite
    - name: Install & build
      run: |
        npm ci
        npm run build          # ⇒ ./dist

    # 3. Añade la clave SSH (para rsync/ssh)
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # 4. Sube solo la carpeta dist/ al DocumentRoot
    - name: Rsync dist to Apache
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        DEST: ${{ vars.TARGET_DIR }}      # p.ej. /var/www/html
      run: |
        rsync -az --delete \
          --no-owner --no-group \
          --rsync-path="sudo rsync" \
          ./dist/ "$USER@$HOST:$DEST"

    # 5. Recarga Apache
    - name: Reload Apache
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh "$USER@$HOST" 'sudo systemctl reload apache2'
